### ISSUE TITLE
Maybe update the gem version?

### ISSUE THREAD

**Issue by Sorrow17** [kameeoze/jruby-poi#21]
Seems the version 0.9.0 has been very dated and needs to be upgraded to the current master version which is compitable with jruby9k.

**Comment by rinkevichjm** [comment]
it is compatible with jruby-9.1.5.0, At least for reading Word files.

**Comment by sdeming** [comment]
I will try to find some time this weekend to get this updated and prepare a new release.

**Comment by rinkevichjm** [comment]
I can send you the changes to do it but they are basically incorporating the 3.15 jars from the POI downloads and adding those jars to the gem. I think it is 6 files including XMLBeans jar

**Comment by sdeming** [comment]
Thanks. I'd gladly accept a pull request for the changes but don't sweat it. I'd be happy to take care of it directly.

**Comment by sdeming** [comment]
All set. Using POI 3.15 jars, incremented version to 1.0 and published. Did some minor house cleaning as well. Tests run against jruby 1.7.23 and jruby 9.1.5.0.
